---

- debug: msg="fp_synchronize_default = {{ fp_synchronize_default }}"
  when: fp_debug
  tags: fp_copy_sync_default

# Sync default
- name: "copy: Check existence of {{ role_path }}/{{ fp_copy_dir }}/default"
  local_action:
    module: stat
    path: "{{ role_path }}/{{ fp_copy_dir }}/default"
  register: default_copy
  tags: fp_copy_sync_default
  # NOTE: playbooks directory IS NOT local_action modules current
  # working directory. Absolute path role_path is needed.

- debug: msg="Directory default exists."
  when:
    - fp_debug
    - default_copy.stat.isdir is defined and default_copy.stat.isdir
  tags: fp_copy_sync_default

- name: "copy: Synchronize default files {{ fp_copy_dir }}/default (relative to playbooks directory)"
  synchronize:
    src: "{{ fp_copy_dir }}/default/"
    dest: "/"
    times: "no"
    perms: "no"
    owner: "no"
    group: "no"
    delete: "{{ fp_synchronize_delete }}"
    checksum: yes
  when:
    - default_copy.stat.exists
    - fp_synchronize_default
  tags: fp_copy_sync_default

# Sync optional
- debug: msg="fp_synchronize_optional = {{ fp_synchronize_optional }}"
  when: fp_debug
  tags: fp_copy_sync_optional

- name: "copy: Check existence of {{ playbook_dir }}/{{ fp_copy_dir }}/{{ rc_conf_hostname }}"
  local_action:
    module: stat
    path: "{{ playbook_dir }}/{{ fp_copy_dir }}/{{ rc_conf_hostname }}"
  register: optional_copy
  tags: fp_copy_sync_optional

- debug: msg="Directory {{ rc_conf_hostname }} exists."
  when:
    - fp_debug
    - optional_copy.stat.isdir is defined and optional_copy.stat.isdir
  tags: fp_copy_sync_optional

- name: "copy: Synchronize host specific files {{ fp_copy_dir }}/{{ rc_conf_hostname }} (relative to playbooks directory)"
  synchronize:
    src: "{{ fp_copy_dir }}/{{ rc_conf_hostname }}/"
    dest: "/"
    times: "no"
    perms: "no"
    owner: "no"
    group: "no"
    delete: "{{ fp_synchronize_delete }}"
    checksum: yes
  when:
    - optional_copy.stat.exists
    - fp_synchronize_optional
  tags: fp_copy_sync_optional

# Unarch default
- name: "copy: Check existence of {{ playbook_dir }}/{{ fp_copy_dir }}/default.tar"
  local_action:
    module: stat
    path: "{{ playbook_dir }}/{{ fp_copy_dir }}/default.tar"
  register: default_copy
  tags: fp_copy_unarch_default

- name: "copy: Untar default files {{ fp_copy_dir }}/default.tar (relative to playbooks directory)"
  unarchive:
    src: "{{ fp_copy_dir }}/default.tar"
    dest: "/"
    keep_newer: "{{ fp_unarchive_keep_newer }}"
  when:
    - default_copy.stat.exists
    - fp_synchronize_default
  tags: fp_copy_unarch_default

# Unarch optional
- name: "copy: Check existence of {{ playbook_dir }}/{{ fp_copy_dir }}/{{ rc_conf_hostname }}.tar"
  local_action:
    module: stat
    path: "{{ playbook_dir }}/{{ fp_copy_dir }}/{{ rc_conf_hostname }}.tar"
  register: optional_copy
  tags: fp_copy_unarch_optional

- name: "copy: Untar host specific files {{ fp_copy_dir }}/{{ rc_conf_hostname }}.tar (relative to playbooks directory)"
  unarchive:
    src: "{{ fp_copy_dir }}/{{ rc_conf_hostname }}.tar"
    dest: "/"
    keep_newer: "{{ fp_unarchive_keep_newer }}"
  when:
    - optional_copy.stat.exists
    - fp_synchronize_optional
  tags: fp_copy_unarch_optional

# EOF
...
