---
- name: "Gitserver: Debug fp_gitserver_debug={{ fp_gitserver_debug }}"
  when: fp_gitserver_debug | bool
  tags: fp_gitserver_debug
  vars:
    msg: |-
      fp_gitserver_install: {{ fp_gitserver_install }}
      fp_gitserver_notify: {{ fp_gitserver_notify }}
      fp_gitserver_service_task: {{ fp_gitserver_service_task }}

      fp_gitserver_dir: {{ fp_gitserver_dir }}
      fp_gitserver_owner: {{ fp_gitserver_owner }}
      fp_gitserver_group: {{ fp_gitserver_group }}

      fp_git_daemon_enable: {{ fp_git_daemon_enable }}
      fp_git_daemon_rcconf:
        {{ fp_git_daemon_rcconf | to_nice_yaml(indent=2) | indent(2) }}
  ansible.builtin.debug:
    msg: "{{ '{}'.format(msg) }}"

- name: "Gitserver: Create {{ fp_gitserver_dir }}"
  tags: fp_gitserver_dir
  ansible.builtin.file:
    state: directory
    path: "{{ fp_gitserver_dir }}"
    owner: "{{ fp_gitserver_owner }}"
    group: "{{ fp_gitserver_group }}"
    mode: "{{ fp_gitserver_dir_mode }}"

- name: "Gitserver: Configure rc.conf"
  tags: fp_gitserver_rcconf
  vars:
    _service: git_daemon
  ansible.builtin.import_tasks: fn/rcconf.yml

# EOF
