---
- name: "Linux: Debug fp_linux_debug={{ fp_linux_debug }}"
  when: fp_linux_debug | bool
  tags: fp_linux_debug
  vars:
    msg: |-
      fp_linux_enable: {{ fp_linux_enable }}
      fp_linux_install: {{ fp_linux_install }}
      fp_linux_notify: {{ fp_linux_notify }}
      fp_linux_service_task: {{ fp_linux_service_task }}

      fp_linux_fstab:
        {{ fp_linux_fstab | to_yaml(indent=2) | indent(2) }}
      fp_linux_lib_dir: {{ fp_linux_lib_dir }}
      fp_linux_lib:
        {{ fp_linux_lib | to_yaml(indent=2) | indent(2) }}
  ansible.builtin.debug:
    msg: "{{ '{}'.format(msg) }}"

- name: "Linux: Configure fstab"
  tags: fp_linux_fstab
  ansible.posix.mount:
    name: "{{ item.name }}"
    src: "{{ item.src }}"
    fstype: "{{ item.fstype }}"
    opts: "{{ item.opts }}"
    state: mounted
  loop: "{{ fp_linux_fstab }}"

- name: "Linux: Create dirs for libraries"
  tags: fp_linux_lib_dir
  ansible.builtin.file:
    state: directory
    path: /compat/linux{{ item.src | dirname }}
    mode: "{{ item.dirmode | d('0755') }}"
  loop: "{{ fp_linux_lib }}"

- name: "Linux: Copy libraries to /compat/linux from {{ fp_linux_lib_dir }}"
  tags: fp_linux_lib_copy
  ansible.builtin.copy:
    src: "{{ fp_linux_lib_dir }}{{ item.src }}"
    dest: /compat/linux{{ item.src }}
    mode: preserve
  loop: "{{ fp_linux_lib }}"

- name: "Linux: Link libraries"
  tags: fp_linux_lib_link
  ansible.builtin.file:
    state: link
    src: /compat/linux{{ item.src }}
    dest: /compat/linux{{ item.link }}
  loop: "{{ fp_linux_lib }}"

- name: "Linux: Configure rc.conf"
  tags: fp_linux_rcconf
  vars:
    _service: linux
  ansible.builtin.import_tasks: fn/rcconf.yml

# EOF
