---
- name: "Loader: Debug fp_loader_debug={{ fp_loader_debug }}"
  when: fp_loader_debug | bool
  tags: fp_loader_debug
  vars:
    msg: |-
      fp_loader_tuneables_warning: {{ fp_loader_tuneables_warning }}
      fp_loader_load_modules: {{ fp_loader_load_modules }}
      fp_loader_conf_file_backup_orig: {{ fp_loader_conf_file_backup_orig }}
      fp_loader_conf_file: {{ fp_loader_conf_file }}
      fp_loader_conf_template: {{ fp_loader_conf_template }}
      fp_loader_conf:
        {{ fp_loader_conf | to_yaml(indent=2) | indent(2) }}
      fp_loader_conf_modules:
        {{ fp_loader_conf_modules | to_yaml(indent=2) | indent(2) }}
      fp_loader_modules:
        {{ fp_loader_modules | to_yaml(indent=2) | indent(2) }}
  ansible.builtin.debug:
    msg: "{{ '{}'.format(msg) }}"

- name: "Loader: Backup orig {{ fp_loader_conf_file }}"
  when: fp_loader_conf_file_backup_orig | bool
  tags: fp_loader_conf_file_backup_orig
  ansible.builtin.command:
    cmd: cp loader.conf loader.conf.orig
    chdir: /boot
    creates: /boot/loader.conf.orig

- name: Configure loader.conf by sysctl
  when: fp_loader_conf_template | length == 0
  tags: fp_loader_conf
  notify: loader message reboot
  block:

    - name: "Loader: Configure by sysctl {{ fp_loader_conf_file }}"
      ansible.posix.sysctl:
        sysctl_file: "{{ fp_loader_conf_file }}"
        name: "{{ item.name }}"
        value: '"{{ item.value | d(omit) }}"'
        state: "{{ item.state | d(omit) }}"
        ignoreerrors: "{{ item.ignoreerrors | d(omit) }}"
      loop: "{{ fp_loader_conf }}"

    - name: "Loader: Configure modules by sysctl {{ fp_loader_conf_file }}"
      ansible.posix.sysctl:
        sysctl_file: "{{ fp_loader_conf_file }}"
        name: "{{ item.name }}_load"
        value: '"{{ item.value | d(omit) }}"'
        state: "{{ item.state | d(omit) }}"
        ignoreerrors: "{{ item.ignoreerrors | d(omit) }}"
      loop: "{{ fp_loader_conf_modules }}"

- name: "Loader: Configure by template {{ fp_loader_conf_file }}"
  when: fp_loader_conf_template | length > 0
  tags: fp_loader_conf
  notify: loader message reboot
  ansible.builtin.template:
    src: "{{ fp_loader_conf_template }}"
    dest: "{{ fp_loader_conf_file }}"
    owner: root
    group: wheel
    mode: "0644"
    backup: "{{ fp_backup }}"

- name: "Loader: Load modules"
  when: fp_loader_load_modules | bool
  changed_when: false
  tags: fp_loader_load_modules
  ansible.builtin.shell:
    cmd: >
      kldstat -q -n {{ item }} || kldload -n {{ item }}
  loop: "{{ fp_loader_modules }}"

- name: Warn when fp_loader_conf keeps also non boot-time tuneables settable via loader.
  when: fp_loader_tuneables_warning | bool
  tags: fp_loader_tuneables_warning
  block:

    - name: "Loader: Get sysctls settable via loader."
      register: result
      changed_when: false
      check_mode: false
      ansible.builtin.command: sysctl -aNT

    - name: "Loader: Warn when fp_sysctl_conf keeps also non boot-time tuneables settable via loader."
      when: fp_loader_non_tuneables | length > 0
      vars:
        fp_loader_non_tuneables: "{{ fp_loader_conf |
                                     map(attribute='name') |
                                     reject('in', result.stdout_lines) | sort }}"
      ansible.builtin.debug:
        msg: >-
          [WARNING] Non boot-time tuneables in fp_loader_conf:
          {{ fp_loader_non_tuneables | to_yaml }}

# EOF
