---
- name: "Motd: Configure /etc/motd"
  tags: fp_motd_create
  ansible.builtin.template:
    src: "{{ fp_motd_conf_template }}"
    dest: "{{ fp_motd_conf_file }}"
    mode: "{{ fp_motd_conf_mode }}"
    backup: "{{ fp_backup }}"

- name: Configure /etc/rc.conf
  vars:
    _path: "{{ fp_rcconfd | bool | ternary(fp_rcconfd_path.motd, '/etc/rc.conf') }}"
  tags: fp_motd_rcconf
  block:

    - name: "Motd: Set update_motd YES in {{ _path }}"
      when: fp_update_motd | bool
      community.general.sysrc:
        path: "{{ _path }}"
        name: update_motd
        value: "YES"

    - name: "Motd: Set update_motd NO in {{ _path }}"
      when: not fp_update_motd | bool
      community.general.sysrc:
        path: "{{ _path }}"
        name: update_motd
        value: "NO"

# NOTES
# By default system info is added to the top of /etc/motd on reboot.
# Set fp_update_motd=False to disable this update.

# EOF
