---
- name: "Motd: Configure /etc/motd"
  tags: fp_motd_create
  ansible.builtin.template:
    src: "{{ fp_motd_conf_template }}"
    dest: "{{ fp_motd_conf_file }}"
    mode: "{{ fp_motd_conf_mode }}"
    backup: "{{ fp_backup }}"

- name: "Motd: Configure rc.conf"
  tags: fp_motd_rcconf
  vars:
    _rcconfd_path: "{{ fp_rcconfd_path[_service] }}"
    _path: "{{ fp_rcconfd | bool | ternary(_rcconfd_path, '/etc/rc.conf') }}"
  community.general.sysrc:
    path: "{{ _path }}"
    name: update_motd
    value: "{{ fp_motd_update | bool | ternary('YES', 'NO') }}"

# EOF
