---
- name: Configure /etc/rc.conf
  vars:
    _path: "{{ fp_rcconfd | bool | ternary(fp_rcconfd_path.ntp, '/etc/rc.conf') }}"
  tags: fp_ntp_rcconf
  block:

    - name: "Ntp: Enable and start ntpd in {{ _path }}"
      when: fp_ntp_enable | bool
      notify: enable and start ntpd
      community.general.sysrc:
        path: "{{ _path }}"
        name: ntpd_enable
        value: "YES"

    - name: "Ntp: Disable and stop ntpd in {{ _path }}"
      when: not fp_ntp_enable | bool
      notify: disable and stop ntpd
      community.general.sysrc:
        path: "{{ _path }}"
        name: ntpd_enable
        value: "NO"

- name: "Ntp: Create /etc/ntp.conf from template"
  tags: fp_ntp_conf
  notify: restart ntpd
  ansible.builtin.template:
    src: "{{ fp_ntp_conf_template }}"
    dest: "{{ fp_ntp_conf_file }}"
    mode: "{{ fp_ntp_conf_mode }}"
    backup: "{{ fp_backup }}"

- name: "Ntp: ntpd {{ state }}"
  tags: fp_ntp_service
  vars:
    state: "{{ fp_ntp_enable | bool | ternary('started', 'stopped') }}"
  ansible.builtin.service:
    name: ntpd
    state: "{{ state }}"

# EOF
