---

- name: "procmail: Remove forwarders"
  ansible.builtin.file:
    state: absent
    dest: "/home/{{ item.user }}/.forward"
  loop: "{{ fp_procmail_forwarders }}"
  when: fp_procmail_forwarders_rebuild|bool
  tags: fp_procmail_forwarders

- name: "procmail: Configure forwarders"
  ansible.builtin.blockinfile:
    create: true
    dest: "/home/{{ item.user }}/.forward"
    owner: "{{ item.user }}"
    mode: '0644'
    marker: '# {mark} ANSIBLE MANAGED BLOCK'
    backup: "{{ fp_backup }}"
    block: |
      "{{ item.forward }}"
  loop: "{{ fp_procmail_forwarders }}"
  tags: fp_procmail_forwarders

- name: "procmail: Configure .procmailrc"
  ansible.builtin.blockinfile:
    create: true
    dest: "/home/{{ item.user }}/.procmailrc"
    owner: "{{ item.user }}"
    mode: '0644'
    marker: '# {mark} ANSIBLE MANAGED BLOCK'
    backup: "{{ fp_backup }}"
    block: |
      SHELL={{ fp_procmail_shell }}
      VERBOSE={{ fp_procmail_verbose }}
      PATH={{ fp_procmail_path }}
      MAILDIR={{ fp_procmail_maildir }}
      DEFAULT=/var/mail/{{ item.user }}
      PMDIR={{ fp_procmail_pmdir }}
      LOGFILE=$PMDIR/pm.log
      LOCKFILE=$PMDIR/.lockfile
      SENDMAIL=/usr/sbin/sendmail
  loop: "{{ fp_procmail_forwarders }}"
  tags: fp_procmail_procmailrc

- name: "procmail: Create .procmail directory"
  ansible.builtin.file:
    state: directory
    mode: '0755'
    path: "/home/{{ item.user }}/.procmail"
    owner: "{{ item.user }}"
  loop: "{{ fp_procmail_forwarders }}"
  tags: fp_procmail_dir

- name: "procmail: Create includerc files"
  ansible.builtin.template:
    src: "procmailrc-includerc-{{ item.template }}.j2"
    dest: "/home/{{ item.user }}/.procmail/{{ item.template }}.rc"
    owner: "{{ item.user }}"
    mode: '0644'
    backup: "{{ fp_backup }}"
  loop: "{{ fp_procmail_includerc }}"
  loop_control:
    label: "{{ item.user }} {{ item.template }}"
  tags: fp_procmail_includerc

- name: "procmail: Include rc files in .procmailrc"
  ansible.builtin.lineinfile:
    create: true
    dest: "/home/{{ item.user }}/.procmailrc"
    owner: "{{ item.user }}"
    mode: '0644'
    line: "INCLUDERC=$PMDIR/{{ item.template }}.rc"
    insertafter: EOF
    backup: "{{ fp_backup }}"
  loop: "{{ fp_procmail_includerc }}"
  loop_control:
    label: "{{ item.user }} {{ item.template }}"
  tags: fp_procmail_includerc

- name: "procmail: Configure {{ fp_procmail_rc_file }}"
  ansible.builtin.template:
    dest: "{{ fp_procmail_rc_file }}"
    owner: root
    mode: '0644'
    src: procmailrc.j2
  vars:
    config: "{{ fp_procmail_rc_conf }}"
  when: fp_procmail_rc_conf|length > 0
  tags: fp_procmail_rc

# EOF
...
