---
- name: Configure smartd
  tags: fp_smartd_conf
  notify: reload smartd
  block:

    - name: "Smartd: Configure smartd.conf"
      ansible.builtin.lineinfile:
        dest: "{{ fp_smartd_conf_file }}"
        regexp: ^\s*DEVICESCAN(.*)$
        state: absent
        backup: "{{ fp_backup }}"

    - name: "Smartd: Configure devices in {{ fp_smartd_conf_file }}"
      ansible.builtin.lineinfile:
        create: true
        dest: "{{ fp_smartd_conf_file }}"
        regexp: "{{ item.regexp }}"
        line: "{{ item.line }}"
        state: "{{ item.state | d(omit) }}"
        owner: "{{ fp_smartd_conf_owner }}"
        group: "{{ fp_smartd_conf_group }}"
        mode: "{{ fp_smartd_conf_mode }}"
        backup: "{{ fp_backup }}"
      loop: "{{ fp_smartd_devices }}"

- name: "Smartd: Configure rc.conf"
  tags: fp_smartd_rcconf
  vars:
    _service: smartd
  ansible.builtin.import_tasks: fn/rcconf.yml

# EOF
