---
- name: "Sshd: Debug fp_sshd_debug={{ fp_sshd_debug }}"
  when: fp_sshd_debug | bool
  tags: fp_sshd_debug
  vars:
    msg: |-
      fp_sshd_enable: {{ fp_sshd_enable }}
      fp_sshd_notify: {{ fp_sshd_notify }}
      fp_sshd_service_task: {{ fp_sshd_service_task }}

      fp_sshd_rcconf:
        {{ fp_sshd_rcconf | to_yaml(indent=2) | indent(2) }}
      fp_sshd_bin: {{ fp_sshd_bin }}
      fp_sshd_conf_file: {{ fp_sshd_conf_file }}
      fp_sshd_conf:
        {{ fp_sshd_conf | to_yaml(indent=2) | indent(2) }}
  ansible.builtin.debug:
    msg: "{{ '{}'.format(msg) }}"

- name: "Sshd: Configure {{ fp_sshd_conf_file }}"
  tags: fp_sshd_config
  notify: reload sshd
  ansible.builtin.lineinfile:
    dest: "{{ fp_sshd_conf_file }}"
    regexp: ^\s*{{ item.key }}\s+(.*)$
    insertbefore: ^\s*#\s*{{ item.key }}
    line: "{{ item.key }} {{ item.value }}"
    backup: "{{ fp_backup }}"
    validate: "{{ fp_sshd_bin }} -t -f %s"
  loop: "{{ fp_sshd_conf }}"

- name: "Sshd: Configure rc.conf"
  tags: fp_sshd_rcconf
  vars:
    _service: sshd
  ansible.builtin.import_tasks: fn/rcconf.yml

# EOF
