---
- name: "Users: Debug (fp_users_debug={{ fp_users_debug }})"
  when: fp_users_debug|bool
  tags: fp_users_debug
  vars:
    msg: |-
      fp_users_debug_classified: {{ fp_users_debug_classified }}
      fp_users_conf:
        {{ fp_users_conf | to_nice_yaml(indent=2) | indent(2) }}
  ansible.builtin.debug:
    msg: "{{ '{}'.format(msg) }}"

- name: "Users: Manage user accounts"
  no_log: "{{ not fp_users_debug_classified }}"
  ansible.builtin.user:
    name: "{{ item.name }}"
    append: "{{ item.append | d(omit) }}"
    authorization: "{{ item.authorization | d(omit) }}"
    comment: "{{ item.comment | d(omit) }}"
    create_home: "{{ item.create_home | d(omit) }}"
    expires: "{{ item.expires | d(omit) }}"
    force: "{{ item.force | d(omit) }}"
    generate_ssh_key: "{{ item.generate_ssh_key | d(omit) }}"
    group: "{{ item.group | d(omit) }}"
    groups: "{{ item.groups | d(omit) }}"
    hidden: "{{ item.hidden | d(omit) }}"
    home: "{{ item.home | d(omit) }}"
    local: "{{ item.local | d(omit) }}"
    login_class: "{{ item.login_class | d(omit) }}"
    move_home: "{{ item.move_home | d(omit) }}"
    non_unique: "{{ item.non_unique | d(omit) }}"
    password: "{{ item.password | d(omit) }}"
    password_lock: "{{ item.password_lock | d(omit) }}"
    profile: "{{ item.profile | d(omit) }}"
    remove: "{{ item.remove | d(omit) }}"
    role: "{{ item.role | d(omit) }}"
    seuser: "{{  item.seuser | d(omit) }}"
    shell: "{{ item.shell | d(omit) }}"
    skeleton: "{{ item.skeleton | d(omit) }}"
    ssh_key_bits: "{{ item.ssh_key_bits | d(omit) }}"
    ssh_key_comment: "{{ item.ssh_key_comment | d(omit) }}"
    ssh_key_file: "{{ item.ssh_key_file | d(omit) }}"
    ssh_key_passphrase: "{{ item.ssh_key_passphrase | d(omit) }}"
    ssh_key_type: "{{ item.ssh_key_type | d(omit) }}"
    state: "{{ item.state | d(omit) }}"
    system: "{{ item.system | d(omit) }}"
    uid: "{{ item.uid | d(omit) }}"
    update_password: "{{ item.update_password | d(omit) }}"
  loop: "{{ fp_users_conf }}"
  loop_control:
    label: "{{ item.name }}"

# EOF
