---

- name: Create annotation-[tasks,handlers,templates].yml
  hosts: localhost
  gather_facts: false
  debugger: on_failed

  vars:

    ansible_python_interpreter: auto_silent
    debug: false
    base_names: "{{ paths | map('basename') }}"
    file_names: "{{ base_names | map('splitext') | map('first') }}"
    my_files: "{{ file_names | zip(base_names) | zip(paths) | map('flatten')
                             | map('zip', ['file_name', 'base_name', 'path'])
                             | map('map', 'reverse')
                             | map('community.general.dict') }}"

  tasks:

    - name: Read vars.
      ansible.builtin.include_vars:
        dir: vars
        extensions: [yml]
        ignore_unknown_extensions: true

    - name: Create annotations.
      vars:
        file: "{{ item }}-list.txt"
        paths: "{{ lookup('file', file).splitlines() }}"
      ansible.builtin.template:
        src: "annotation-{{ item }}.yml.j2"
        dest: "annotation-{{ item }}.yml"
        mode: "0644"
      loop:
        - tasks
        - handlers
        - templates

# EOF
...
