---
# nfs

- name: enable and start nfs client
  ansible.builtin.service: name=nfsclient state=started enabled=true

- name: disable and stop nfs client
  ansible.builtin.service: name=nfsclient state=stopped enabled=false

- name: restart nfs client
  ansible.builtin.service: name=nfsclient state=restarted
  when: fp_nfs_enable|bool
