---
# ntpd

- name: enable and start ntpd
  ansible.builtin.service: name=ntpd state=started enabled=true

- name: disable and stop ntpd
  ansible.builtin.service: name=ntpd state=stopped enabled=false

- name: restart ntpd
  ansible.builtin.service: name=ntpd state=restarted
  when: fp_ntp_enable|bool
