---
- name: "Mdconfig-attach-disk: Attach memory disk"
  vars:
    al_mdconfig_file: "{{ item[_fp_mount_task] }}" # noqa: var-naming[no-role-prefix]
  ansible.builtin.include_role:
    name: "{{ fp_ansible_lib[ansible_role_name] }}"
    tasks_from: al_mdconfig.yml

# EOF
