---
fp_hosts: false
fp_hosts_debug: false

fp_hosts_sanity: true
fp_hosts_sanity_quiet: true
fp_hosts_sanity_valid_ip: true
fp_hosts_sanity_unique_fqdn: true
fp_hosts_sanity_valid_fqdn: false # required: fqdn>=1.5.1 (PyPI)
fp_hosts_fqdn_allow_underscores: true

fp_hosts_conf_file: /etc/hosts
fp_hosts_conf_template: hosts.j2
fp_hosts_localhost_ipv4: 127.0.0.1
fp_hosts_localhost_ipv6: ::1
fp_hosts_conf: []
