---

- name: Create source/annotation-[tasks,handlers,templates].rst
  hosts: localhost
  gather_facts: false
  debugger: on_failed

  vars:

    ansible_python_interpreter: auto_silent

  tasks:

    - name: Tasks
      tags: tasks
      block:

        - name: Include annotation/annotation-tasks.yml
          ansible.builtin.include_vars:
            file: annotation/annotation-tasks.yml

        - name: Create source/annotation-tasks.rst
          ansible.builtin.template:
            src: annotation/annotation-tasks.rst.j2
            dest: source/annotation-tasks.rst
            mode: "0644"

    - name: Handlers
      tags: handlers
      block:

        - name: Include annotation/annotation-handlers.yml
          ansible.builtin.include_vars:
            file: annotation/annotation-handlers.yml

        - name: Create source/annotation-handlers.rst
          ansible.builtin.template:
            src: annotation/annotation-handlers.rst.j2
            dest: source/annotation-handlers.rst
            mode: "0644"

    - name: Templates
      tags: templates
      block:

        - name: Include annotation/annotation-templates.yml
          ansible.builtin.include_vars:
            file: annotation/annotation-templates.yml

        - name: Create source/annotation-templates.rst
          ansible.builtin.template:
            src: annotation/annotation-templates.rst.j2
            dest: source/annotation-templates.rst
            mode: "0644"

# EOF
...
